#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v ufw >/dev/null 2>&1; then
            ufw delete allow from 192.168.10.0/24 to any port 22 proto tcp \
                >/dev/null 2>&1 || true
        fi
        ;;
esac

case "$1" in
    purge)
        rm -f /var/lib/AccountsService/users/aimsit
        if getent passwd aimsit >/dev/null; then
            deluser --quiet aimsit >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
